const ActionTypes = {
    LOAD_GRAPH_START: "LOAD_GRAPH_START",
    LOAD_GRAPH_SUCCESS: "LOAD_GRAPH_SUCCESS",
    TOGGLE_BOOK: "TOGGLE_BOOK",
    SET_HOVERED_NODE: "SET_HOVERED_NODE",
    SET_TRANSFORM: "SET_TRANSFORM",
    SET_THEME: "SET_THEME",
    RESIZE: "RESIZE",
};

export { ActionTypes };
